### ISSUE TITLE
Why do we use ZYXC instead of ZXYC?

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro-ilastik#5]
@JoshuaHess12 Why do we use ZYXC instead of ZXYC?
https://github.com/labsyspharm/mcmicro-ilastik/blob/d05f09f8d55f4f42c19e2fc9b6ff2e23c60c2ea4/IlastikPrepOME.py#L54

If there is no specific reason, I will change the axis for the next version.

**Comment by DenisSch** [comment]
If no objectives, I changed it here:
https://github.com/labsyspharm/mcmicro-ilastik/commit/a8a4634ade819a9d6f0cc171404f5b7cdae48e42

**Comment by JoshuaHess12** [comment]
Just checked this out with an example dataset -- the ilastik plugin for FIJI default axis order on my machine is t(z)xyc:
<img width="387" alt="Screen Shot 2020-07-17 at 12 34 57 PM" src="https://user-images.githubusercontent.com/46495012/87809888-1ed9e700-c82a-11ea-9c31-98a793a3d000.png">

However, the default behavior for the lastik GUI is t(z)yxc:
<img width="850" alt="Screen Shot 2020-07-17 at 12 35 41 PM" src="https://user-images.githubusercontent.com/46495012/87810006-4e88ef00-c82a-11ea-8b3a-bb1a074d4265.png">

I believe the module was originally set to match the axis order of the Ilastik GUI.

**Comment by DenisSch** [comment]
Yeah, which is weird since it should be X before Y...I removed the swap for now since otherwise it will not align with the original image.

**Comment by JoshuaHess12** [comment]
That works -- feel free to re-open the issue and tag me if there are any
problems.
