### ISSUE TITLE
Specify channel ID

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro-ilastik#8]
Currently you just specify the amount of channels to use. We should enable to select specific channels.

**Comment by DenisSch** [comment]
@JoshuaHess12 Would you have time to implement this?
E.g. I would like to say `---num_channels 40` or `--num_channels 1 2 3 5 12 15 40`

**Comment by DenisSch** [comment]
So if you specify more than one, it is used as channel ID or we could just do `[1 2 3 5 12 15 40]`

**Comment by JoshuaHess12** [comment]
This could could be fixed by removing the num_channels argument. Instead we could just have channel index as an input and read all channels given one at a time. For now, the num_channels argument is only used to determine whether channels are read and exported two at a time or one at a time. What do you think?

**Comment by DenisSch** [comment]
Please proceed as discussed:
Keep `num_channels` and add a new parameter. Make sure to include a check that amount of channels and num_channels are equal if both are provided.

**Comment by DenisSch** [comment]
testing #9 now

**Comment by DenisSch** [comment]
@JoshuaHess12 `channelIDs` is an optional input - correct? Just checking in terms of backwards compatibility

**Comment by JoshuaHess12** [comment]
'channelIDs' is an optional input. If it is not given, then the first n
channels are taken according to the 'num_channels' input parameter. This
should be fine for backwards compatibility as long as the 'nuclei_index'
for cropping is in the first n channels. If both 'num_channels' and
'channelIDs' are missing, an error will be raised.

**Comment by DenisSch** [comment]
Perfect - tested and included into mcmicro!
